using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using SkylinePrism.Core.BatchCorrection;
using SkylinePrism.Tests.TestSupport;
using Xunit;

namespace SkylinePrism.Tests.BatchCorrection;

/// <summary>
/// PRISM's ComBat against the implementation it claims to be based on: R's <c>sva::ComBat</c>
/// (3.58.0). Fixtures are generated by <c>tests/fixtures/sva/generate.R</c>.
/// <para>
/// The cross-language Python-vs-C# goldens cannot do this job. They only prove the two PRISM
/// engines agree - which they did for years while both propagated a single missing value into an
/// all-NaN matrix, something sva has never done. An external reference is the only thing that
/// catches a shared wrong answer.
/// </para>
/// <para>
/// Two of the five fixtures have no golden matrix because <b>sva itself errors</b> on them. Those
/// are recorded as such: PRISM handling them is an extension of sva, not a divergence from it.
/// </para>
/// </summary>
public class SvaGoldenTests
{
    private static string Dir => Fixtures.Path2("sva");

    /// <summary>
    /// A dense matrix is the normal PRISM input - Skyline integrates imputed peak boundaries for
    /// every replicate - so this is the case that has to match, and it does.
    /// </summary>
    [Fact]
    public void Dense_ReproducesSva()
    {
        var (worst, _) = CompareWithSva("dense");
        Assert.True(worst < 1e-6, $"worst relative difference from sva: {worst:E3}");
    }

    /// <summary>
    /// The bug this whole exercise started from. sva leaves each missing value exactly where it is
    /// (82 in, 82 out); PRISM used to return 680 of 680 cells as NaN.
    /// <para>
    /// The observed cells do NOT match sva here, by design: sva switches <c>var_pooled</c> to
    /// <c>rowVars(na.rm = TRUE)</c> (ddof 1) as soon as anything is missing, and PRISM does not
    /// switch. Following it would mean one peptide missing from one document shifts every corrected
    /// value in the cohort by ~0.3%. This test pins both halves - that missing values stay local,
    /// AND that the numeric gap is exactly the denominator, by showing it vanishes when PRISM is
    /// given sva's other denominator.
    /// </para>
    /// </summary>
    [Fact]
    public void Sparse_KeepsMissingValuesLocal_AndDiffersOnlyByTheDenominator()
    {
        var (input, _, _) = ReadMatrix(Path.Combine(Dir, "sparse_input.csv"));
        var (sva, _, _) = ReadMatrix(Path.Combine(Dir, "sparse_sva.csv"));
        var missingIn = Count(input, double.IsNaN);
        var missingOut = Count(sva, double.IsNaN);
        Assert.True(missingIn > 0, "fixture should contain missing values");
        Assert.Equal(missingIn, missingOut); // sva keeps them local...

        var (asShipped, comparedCells) = CompareWithSva("sparse");
        Assert.Equal(input.Length - missingIn, comparedCells); // ...and so must PRISM
        Assert.InRange(asShipped, 1e-4, 1e-2); // the documented denominator gap, and no more

        // Give PRISM sva's missing-value denominator and the gap disappears - proving that is the
        // whole of the difference, not an unknown drift hiding behind a loose bound.
        var withSvaDenominator = CompareWithSva("sparse", varPooledDdof: 1).Worst;
        Assert.True(withSvaDenominator < 1e-9,
            $"with sva's own ddof=1 denominator PRISM should match it exactly: {withSvaDenominator:E3}");
    }

    /// <summary>
    /// A feature that is constant within one batch. sva drops it entirely and returns it unchanged;
    /// PRISM keeps the location correction the data does support and skips only the scale. This is
    /// the deliberate divergence recorded as rows 2-4 in PRISM-BUG-combat-nan-propagation.md.
    /// <para>
    /// <b>The divergence is NOT confined to those features.</b> sva computes its priors
    /// (<c>gammaBar</c>, <c>t2</c>, <c>aPrior</c>, <c>bPrior</c>) over the 38 features it kept;
    /// PRISM computes them over all 40, because a constant-in-batch feature still has a perfectly
    /// well-defined <c>gammaHat</c>. Different feature sets, different shrinkage - so every feature
    /// moves a little. That is the real price of keeping them, and it is pinned here rather than
    /// discovered later.
    /// </para>
    /// </summary>
    [Fact]
    public void ConstantWithinBatch_DivergesFromSva_DeliberatelyAndOnlyThere()
    {
        var (input, batchLabels, _) = ReadCase("constant_in_batch");
        var (sva, _, _) = ReadMatrix(Path.Combine(Dir, "constant_in_batch_sva.csv"));
        var prism = ComBat.Run(input, batchLabels);

        var nSamples = input.GetLength(1);
        var divergent = new List<int>();
        var worstElsewhere = 0.0;
        for (var f = 0; f < input.GetLength(0); f++)
        {
            var svaUnchanged = true;
            var worstRow = 0.0;
            for (var s = 0; s < nSamples; s++)
            {
                if (sva[f, s] != input[f, s])
                    svaUnchanged = false;
                worstRow = Math.Max(worstRow, RelativeDifference(sva[f, s], prism[f, s]));
            }
            if (svaUnchanged)
                divergent.Add(f);
            else
                worstElsewhere = Math.Max(worstElsewhere, worstRow);
        }

        // The generator makes exactly two such features (F0001, F0002).
        Assert.Equal(2, divergent.Count);

        // Everything else still tracks sva closely, but not exactly - the two extra features shift
        // the priors. Bounded and asserted from both sides: a much LARGER gap would mean something
        // beyond the prior shift diverged, a much smaller one would mean the fixture stopped
        // exercising the case at all.
        Assert.InRange(worstElsewhere, 1e-4, 5e-2);

        foreach (var f in divergent)
        {
            var moved = false;
            for (var s = 0; s < nSamples && !moved; s++)
                moved = prism[f, s] != input[f, s];
            Assert.True(moved,
                $"feature {f} is constant in one batch, but its location effect is estimable - "
                + "PRISM should still correct it rather than pass it through like sva");
        }
    }

    /// <summary>
    /// Cases sva cannot express: a feature with one observation in a batch (its <c>delta.hat</c>
    /// becomes NA and sva's uncapped <c>while (change &gt; conv)</c> loop dies on it), and a feature
    /// absent from a batch entirely (<c>Beta.NA</c> hits a singular design). PRISM must produce
    /// numbers instead of failing, and must not turn the rest of the matrix into NaN doing it.
    /// </summary>
    [Theory]
    [InlineData("single_obs")]
    [InlineData("absent")]
    public void SvaCannotExpress_PrismHandlesIt(string name)
    {
        // The fixture asserts its own premise: sva really did fail here.
        var errorFile = Path.Combine(Dir, name + "_sva_error.txt");
        Assert.True(File.Exists(errorFile),
            $"expected {name}_sva_error.txt - regenerate with tests/fixtures/sva/generate.R");
        Assert.False(File.Exists(Path.Combine(Dir, name + "_sva.csv")));

        var (input, batchLabels, _) = ReadCase(name);
        var prism = ComBat.Run(input, batchLabels);

        // Missing stays exactly where it was; nothing else becomes NaN.
        for (var f = 0; f < input.GetLength(0); f++)
            for (var s = 0; s < input.GetLength(1); s++)
                Assert.Equal(double.IsNaN(input[f, s]), double.IsNaN(prism[f, s]));
    }

    // ---------------------------------------------------------------- helpers

    private static (double Worst, int ComparedCells) CompareWithSva(
        string name, int varPooledDdof = ComBat.VarPooledDdof)
    {
        var (input, batchLabels, _) = ReadCase(name);
        var (sva, _, _) = ReadMatrix(Path.Combine(Dir, name + "_sva.csv"));
        var prism = ComBat.Run(input, batchLabels, parPrior: true, meanOnly: false,
            diagnostics: null, varPooledDdof: varPooledDdof);

        Assert.Equal(sva.GetLength(0), prism.GetLength(0));
        Assert.Equal(sva.GetLength(1), prism.GetLength(1));

        var worst = 0.0;
        var compared = 0;
        for (var f = 0; f < sva.GetLength(0); f++)
        for (var s = 0; s < sva.GetLength(1); s++)
        {
            if (double.IsNaN(sva[f, s]) || double.IsNaN(prism[f, s]))
            {
                Assert.True(double.IsNaN(sva[f, s]) && double.IsNaN(prism[f, s]),
                    $"{name}[{f},{s}]: sva {sva[f, s]} vs PRISM {prism[f, s]}");
                continue;
            }
            worst = Math.Max(worst, RelativeDifference(sva[f, s], prism[f, s]));
            compared++;
        }
        Assert.True(compared > 0, "compared nothing");
        return (worst, compared);
    }

    private static (double[,] Matrix, List<string> BatchLabels, List<string> Samples) ReadCase(string name)
    {
        var (matrix, samples, _) = ReadMatrix(Path.Combine(Dir, name + "_input.csv"));
        var batchOf = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var line in File.ReadAllLines(Path.Combine(Dir, name + "_batches.csv")).Skip(1))
        {
            var parts = line.Split(',');
            batchOf[parts[0]] = parts[1];
        }
        return (matrix, samples.Select(s => batchOf[s]).ToList(), samples);
    }

    /// <summary>Read a features x samples CSV written by generate.R (first column = feature name).</summary>
    private static (double[,] Matrix, List<string> Samples, List<string> Features) ReadMatrix(string path)
    {
        var lines = File.ReadAllLines(path);
        var samples = lines[0].Split(',').Skip(1).ToList();
        var features = new List<string>(lines.Length - 1);
        var matrix = new double[lines.Length - 1, samples.Count];
        for (var i = 1; i < lines.Length; i++)
        {
            var parts = lines[i].Split(',');
            features.Add(parts[0]);
            for (var j = 0; j < samples.Count; j++)
                matrix[i - 1, j] = double.Parse(parts[j + 1], CultureInfo.InvariantCulture);
        }
        return (matrix, samples, features);
    }

    private static int Count(double[,] m, Func<double, bool> predicate)
    {
        var n = 0;
        foreach (var v in m)
            if (predicate(v))
                n++;
        return n;
    }

    private static double RelativeDifference(double expected, double actual)
    {
        if (expected == actual)
            return 0;
        return Math.Abs(expected - actual) / Math.Max(Math.Abs(expected), 1e-30);
    }
}
